### ISSUE TITLE
HSQLDB upgrade script fails

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-userStatus-plugin#9]
Looks like HSQLDB uses alter instead of modify.

**Comment by pras14587** [comment]
What happen, when not updated the plugin?
Please share.
Is it reverse compatible?

**Comment by wrooot** [comment]
Not sure what you mean. This change is only in new version of plugin and this only affects when updating database. Do you want to update database, but still use older plugin? I think it should work as only database fields were updated to store longer values, no change to plugin itself as far as I remember.

**Comment by pras14587** [comment]
Okay thanks, means things are reverse compatible.
If I update the plugin, there is no need to update the database,

**Comment by wrooot** [comment]
If you update the plugin, it will update the database. To be precise, it will update some field related to UserStatus plugin in the database to let them store longer IPv6 strings.

**Comment by pras14587** [comment]
yes, thank you so much.

**Comment by pras14587** [comment]
Hi wroot, I want to implement chat using BOSH for Desktop, as per me you have also contributed on converse.js. I am facing many disconnection issues using Strophe js.
So, please help me out.

**Comment by wrooot** [comment]
This is not a place for such inquiry. Please use forums for this.
